image:
  repository: cassini-web
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: cassini-assistant.online
  className: traefik

tls:
  enabled: true
  secretName: web-tls
